import { useState } from 'react';
import { FileText, Sparkles, Edit3, Save, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useAINotes } from '@/hooks/useAIContent';
import { ScrollArea } from '@/components/ui/scroll-area';

interface LessonNotesProps {
  lessonId: string;
  lessonTitle: string;
}

export function LessonNotes({ lessonId, lessonTitle }: LessonNotesProps) {
  const { notes, isLoading, generateNotes, updatePersonalNotes } = useAINotes(lessonId);
  const [isEditing, setIsEditing] = useState(false);
  const [personalNotesText, setPersonalNotesText] = useState(notes?.user_personal_notes || '');

  const handleGenerateNotes = () => {
    generateNotes.mutate(lessonTitle);
  };

  const handleSavePersonalNotes = () => {
    updatePersonalNotes.mutate(personalNotesText);
    setIsEditing(false);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  if (!notes?.ai_generated_content) {
    return (
      <Card className="border-dashed">
        <CardContent className="flex flex-col items-center justify-center py-12 space-y-4">
          <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center">
            <Sparkles className="w-8 h-8 text-primary" />
          </div>
          <div className="text-center space-y-2">
            <h3 className="font-semibold text-lg">Generate AI Notes</h3>
            <p className="text-muted-foreground text-sm max-w-md">
              Get comprehensive notes for this lesson generated by AI, covering all key concepts and examples.
            </p>
          </div>
          <Button 
            onClick={handleGenerateNotes}
            disabled={generateNotes.isPending}
            className="gap-2"
          >
            {generateNotes.isPending ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                Generate Notes
              </>
            )}
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <Tabs defaultValue="ai" className="w-full">
      <TabsList className="grid w-full grid-cols-2">
        <TabsTrigger value="ai" className="gap-2">
          <FileText className="w-4 h-4" />
          AI Notes
        </TabsTrigger>
        <TabsTrigger value="personal" className="gap-2">
          <Edit3 className="w-4 h-4" />
          My Notes
        </TabsTrigger>
      </TabsList>

      <TabsContent value="ai" className="mt-4">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-lg flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-primary" />
              AI-Generated Notes
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ScrollArea className="h-[400px] pr-4">
              <div className="prose prose-sm max-w-none dark:prose-invert">
                <div dangerouslySetInnerHTML={{ __html: formatMarkdown(notes.ai_generated_content) }} />
              </div>
            </ScrollArea>
          </CardContent>
        </Card>
      </TabsContent>

      <TabsContent value="personal" className="mt-4">
        <Card>
          <CardHeader className="pb-3 flex flex-row items-center justify-between">
            <CardTitle className="text-lg">Personal Notes</CardTitle>
            {!isEditing ? (
              <Button variant="outline" size="sm" onClick={() => setIsEditing(true)}>
                <Edit3 className="w-4 h-4 mr-2" />
                Edit
              </Button>
            ) : (
              <Button 
                size="sm" 
                onClick={handleSavePersonalNotes}
                disabled={updatePersonalNotes.isPending}
              >
                {updatePersonalNotes.isPending ? (
                  <Loader2 className="w-4 h-4 animate-spin mr-2" />
                ) : (
                  <Save className="w-4 h-4 mr-2" />
                )}
                Save
              </Button>
            )}
          </CardHeader>
          <CardContent>
            {isEditing ? (
              <Textarea
                value={personalNotesText}
                onChange={(e) => setPersonalNotesText(e.target.value)}
                placeholder="Add your own notes, key points to remember, or questions..."
                className="min-h-[400px] resize-none"
              />
            ) : (
              <ScrollArea className="h-[400px]">
                {notes.user_personal_notes ? (
                  <p className="whitespace-pre-wrap">{notes.user_personal_notes}</p>
                ) : (
                  <p className="text-muted-foreground italic">
                    No personal notes yet. Click Edit to add your own notes.
                  </p>
                )}
              </ScrollArea>
            )}
          </CardContent>
        </Card>
      </TabsContent>
    </Tabs>
  );
}

function formatMarkdown(text: string): string {
  return text
    .replace(/^### (.+)$/gm, '<h3 class="text-lg font-semibold mt-4 mb-2">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 class="text-xl font-semibold mt-6 mb-3">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 class="text-2xl font-bold mt-6 mb-4">$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^- (.+)$/gm, '<li class="ml-4">$1</li>')
    .replace(/(<li.*<\/li>\n?)+/g, '<ul class="list-disc my-2">$&</ul>')
    .replace(/\n\n/g, '</p><p class="my-2">')
    .replace(/^(.+)$/gm, (match) => {
      if (match.startsWith('<')) return match;
      return `<p class="my-2">${match}</p>`;
    });
}
