-- Insert existing legacy blog articles into the blog_articles table

INSERT INTO public.blog_articles 
(slug, title, meta_title, meta_description, excerpt, category, read_time, published_at, updated_at, featured, image, keywords, program, published) 
VALUES
('olevel-study-guide', 'Complete Guide to O-Level Success in Pakistan', 'O-Level Study Guide | Cambridge O-Level Preparation Pakistan', 'Learn how to prepare for Cambridge O-Level exams with study tips, past papers, subject guides, and exam strategies for students in Pakistan.', 'Master your Cambridge O-Level exams with this comprehensive study guide covering all subjects, study strategies, past paper techniques, and expert tips for Pakistani students.', 'Study Guide', '15 min read', '2026-03-10', '2026-03-16', true, '/og-image.png', ARRAY['O Level', 'Cambridge O Level', 'O Level preparation', 'O Level study guide', 'O Level exam preparation Pakistan'], 'O Level', true),

('olevel-past-papers', 'How to Use O-Level Past Papers Effectively for Exam Success', 'O-Level Past Papers Guide | Best Practice Strategy for Cambridge Exams', 'Discover the best strategies for using Cambridge O-Level past papers to boost your exam scores. Learn marking scheme analysis and time management tips.', 'Past papers are the single most effective tool for O-Level exam preparation. Learn how to use them strategically to maximize your scores across all subjects.', 'Exam Tips', '10 min read', '2026-03-08', '2026-03-15', false, '/og-image.png', ARRAY['O Level past papers', 'Cambridge past papers', 'O Level exam practice', 'O Level mock exams'], 'O Level', true),

('how-to-get-a-star-in-olevel', 'How to Get A* in O-Level: Proven Strategies from Top Scorers', 'How to Get A* in O-Level | Top Scorer Tips & Strategies', 'Learn proven strategies from A* students to achieve top grades in Cambridge O-Level exams. Expert tips on study habits, revision, and exam technique.', 'Achieving an A* in O-Levels requires more than hard work — it requires smart strategies. Here are proven techniques from students who consistently score top grades.', 'Study Tips', '12 min read', '2026-03-05', '2026-03-14', false, '/og-image.png', ARRAY['A star O Level', 'O Level top grades', 'O Level revision', 'O Level exam tips'], 'O Level', true),

('olevel-mathematics-tips', 'O-Level Mathematics: Complete Topic Guide & Scoring Tips', 'O-Level Mathematics Tips | Score A* in Cambridge Math', 'Master O-Level Mathematics with topic-by-topic study tips, formula sheets, and practice strategies. Ace algebra, geometry, trigonometry and statistics.', 'Mathematics is one of the most scoring O-Level subjects if you approach it right. This guide covers every major topic with practical tips to boost your math grade.', 'Subject Guide', '14 min read', '2026-03-01', '2026-03-13', false, '/og-image.png', ARRAY['O Level mathematics', 'O Level math tips', 'Cambridge math', 'O Level algebra', 'O Level trigonometry'], 'O Level', true),

('olevel-exam-preparation-pakistan', 'O-Level Exam Preparation in Pakistan: Ultimate 2026 Guide', 'O-Level Exam Preparation Pakistan 2026 | Complete Guide', 'The ultimate guide to O-Level exam preparation for Pakistani students. Covers exam registration, subject choices, study resources, and preparation timeline.', 'Everything Pakistani students need to know about preparing for Cambridge O-Level exams — from choosing subjects to creating a study plan and finding the best resources.', 'Guide', '11 min read', '2026-02-25', '2026-03-12', false, '/og-image.png', ARRAY['O Level Pakistan', 'O Level exam preparation Pakistan', 'Cambridge O Level Pakistan', 'O Level registration Pakistan'], 'O Level', true),

('olevel-ict-computer-science-guide', 'O-Level ICT & Computer Science: Ultimate Revision Guide 2026', 'O-Level ICT Guide | Cambridge Computer Science Tips & Topics', 'Complete O-Level ICT and Computer Science revision guide covering binary, databases, programming, networking, and cyber security for Cambridge exams.', 'ICT and Computer Science are high-scoring O-Level subjects with the right preparation. This guide breaks down every major topic with practical revision tips and common exam traps.', 'Subject Guide', '13 min read', '2026-04-01', '2026-04-08', false, '/og-image.png', ARRAY['O Level ICT', 'O Level Computer Science', 'Cambridge ICT revision', 'O Level programming', 'O Level binary', 'O Level networking'], 'O Level', true),

('olevel-time-management-exam-day', 'O-Level Exam Day Time Management: How to Finish Every Paper', 'O-Level Time Management | Exam Day Strategies to Finish on Time', 'Learn proven time management strategies for Cambridge O-Level exam day. How to allocate time per question, avoid common pitfalls, and finish every paper confidently.', 'Running out of time is the #1 reason students lose marks in O-Level exams. Learn how to pace yourself, allocate time correctly, and handle tough questions without panic.', 'Exam Tips', '9 min read', '2026-04-03', '2026-04-09', false, '/og-image.png', ARRAY['O Level time management', 'exam day tips', 'Cambridge exam strategy', 'O Level paper time', 'finish O Level paper'], 'O Level', true),

('olevel-physics-chemistry-biology-tips', 'O-Level Sciences: Physics, Chemistry & Biology Scoring Guide', 'O-Level Science Tips | Physics Chemistry Biology Exam Guide', 'Score top grades in O-Level Physics, Chemistry, and Biology with targeted revision strategies, formula tips, and practical exam techniques for Cambridge students.', 'Science subjects require a blend of conceptual understanding and exam technique. Here''s your complete guide to acing O-Level Physics, Chemistry, and Biology.', 'Subject Guide', '16 min read', '2026-04-05', '2026-04-10', false, '/og-image.png', ARRAY['O Level Physics', 'O Level Chemistry', 'O Level Biology', 'O Level science tips', 'Cambridge science revision'], 'O Level', true),

('olevel-english-language-writing-tips', 'O-Level English Language: How to Write Perfect Essays & Summaries', 'O-Level English Tips | Essay Writing & Summary Techniques', 'Master O-Level English Language with proven essay writing techniques, summary skills, and comprehension strategies. Score A* with these practical tips.', 'English Language is a core O-Level subject where strong writing skills make all the difference. Learn how to craft compelling essays, accurate summaries, and score top marks in comprehension.', 'Subject Guide', '12 min read', '2026-04-07', '2026-04-11', false, '/og-image.png', ARRAY['O Level English', 'O Level essay writing', 'O Level summary', 'Cambridge English tips', 'O Level comprehension'], 'O Level', true),

('olevel-accounting-revision-tips', 'O-Level Accounting: Master Double Entry & Financial Statements', 'O-Level Accounting Guide | Double Entry & Balance Sheet Tips', 'Complete O-Level Accounting revision guide covering double entry bookkeeping, financial statements, ratios, and common exam mistakes to avoid.', 'Accounting is a logical subject that rewards practice. This guide covers double entry bookkeeping, trial balances, financial statements, and the most common mistakes students make in exams.', 'Subject Guide', '14 min read', '2026-04-09', '2026-04-11', false, '/og-image.png', ARRAY['O Level Accounting', 'O Level double entry', 'Cambridge Accounting tips', 'O Level financial statements', 'O Level balance sheet'], 'O Level', true),

('igcse-vs-olevel', 'IGCSE vs O-Level in Pakistan: Which Should You Choose?', 'IGCSE vs O-Level Pakistan | Full Comparison Guide 2026', 'Compare Cambridge IGCSE and O-Level in Pakistan: syllabus, grading, university acceptance, difficulty, and which qualification suits you best.', 'Torn between Cambridge IGCSE and O-Level? This complete comparison covers syllabus differences, grading, difficulty, university recognition, and how to decide.', 'IGCSE', '12 min read', '2026-04-14', '2026-04-14', false, '/og-image.png', ARRAY['IGCSE', 'IGCSE Pakistan', 'IGCSE vs O Level', 'Cambridge IGCSE', 'IGCSE guide'], 'IGCSE', true),

('igcse-preparation-guide', 'Complete Cambridge IGCSE Preparation Guide for Pakistani Students', 'IGCSE Preparation Guide | Cambridge IGCSE Study Tips Pakistan', 'Master Cambridge IGCSE with subject-wise study plans, past paper strategies, and revision techniques for Pakistani students.', 'A step-by-step IGCSE preparation plan covering Math, Physics, Chemistry, Biology, English, and ICT — with past paper strategies and revision timelines.', 'IGCSE', '14 min read', '2026-04-16', '2026-04-16', false, '/og-image.png', ARRAY['IGCSE preparation', 'Cambridge IGCSE study', 'IGCSE Math', 'IGCSE Physics', 'IGCSE past papers'], 'IGCSE', true),

('igcse-past-papers-strategy', 'How to Use IGCSE Past Papers to Score A* in Every Subject', 'IGCSE Past Papers Strategy | Score A* with Cambridge IGCSE Practice', 'Discover the smartest way to use Cambridge IGCSE past papers, mark schemes and examiner reports to secure A* grades.', 'IGCSE past papers are gold — if you use them the right way. Learn the exact technique to extract maximum marks from every Cambridge IGCSE past paper.', 'IGCSE', '10 min read', '2026-04-18', '2026-04-18', false, '/og-image.png', ARRAY['IGCSE past papers', 'IGCSE mark scheme', 'IGCSE A star', 'Cambridge IGCSE practice', 'IGCSE revision'], 'IGCSE', true),

('igcse-math-tips', 'IGCSE Mathematics: Top 10 Tips to Ace the Exam', 'IGCSE Mathematics Tips | Score A* in Cambridge IGCSE Math', 'Boost your IGCSE Maths grade with 10 exam-tested strategies covering algebra, geometry, statistics and problem solving.', 'IGCSE Mathematics rewards preparation. These 10 tips cover algebra, geometry, statistics, and exam technique so you enter the paper confident.', 'IGCSE', '11 min read', '2026-04-20', '2026-04-20', false, '/og-image.png', ARRAY['IGCSE Maths', 'IGCSE Mathematics tips', 'IGCSE 0580', 'Cambridge IGCSE Math', 'IGCSE algebra'], 'IGCSE', true)
ON CONFLICT (slug) DO UPDATE SET 
  title = EXCLUDED.title,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  excerpt = EXCLUDED.excerpt,
  category = EXCLUDED.category,
  read_time = EXCLUDED.read_time,
  published_at = EXCLUDED.published_at,
  updated_at = EXCLUDED.updated_at,
  featured = EXCLUDED.featured,
  image = EXCLUDED.image,
  keywords = EXCLUDED.keywords,
  program = EXCLUDED.program,
  published = EXCLUDED.published;
