import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { FileDown, Loader2 } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { format, subDays, startOfWeek, endOfWeek } from 'date-fns';

interface WeeklyReportExporterProps {
  profile: {
    display_name: string | null;
    xp_points: number;
    level: number;
    streak_days: number;
    coins: number;
  } | null;
}

export const WeeklyReportExporter = ({ profile }: WeeklyReportExporterProps) => {
  const { user } = useAuth();
  const [isExporting, setIsExporting] = useState(false);

  const generateReport = async () => {
    if (!user || !profile) return;

    setIsExporting(true);

    try {
      const weekStart = startOfWeek(new Date());
      const weekEnd = endOfWeek(new Date());

      // Fetch weekly data
      const [lessonsResult, quizResult, goalsResult] = await Promise.all([
        supabase
          .from('lesson_progress')
          .select('*')
          .eq('user_id', user.id)
          .gte('last_accessed_at', weekStart.toISOString())
          .lte('last_accessed_at', weekEnd.toISOString()),
        supabase
          .from('quiz_attempts')
          .select('*')
          .eq('user_id', user.id)
          .gte('created_at', weekStart.toISOString())
          .lte('created_at', weekEnd.toISOString()),
        supabase
          .from('daily_goals')
          .select('*')
          .eq('user_id', user.id)
          .gte('goal_date', format(weekStart, 'yyyy-MM-dd'))
          .lte('goal_date', format(weekEnd, 'yyyy-MM-dd')),
      ]);

      const lessons = lessonsResult.data || [];
      const quizzes = quizResult.data || [];
      const goals = goalsResult.data || [];

      const lessonsCompleted = lessons.filter(l => l.lesson_completed).length;
      const quizAttempts = quizzes.length;
      const correctAnswers = quizzes.filter(q => q.is_correct).length;
      const xpEarned = quizzes.reduce((sum, q) => sum + (q.xp_earned || 0), 0);
      const daysWithProgress = goals.filter(g => g.earned_xp > 0).length;

      // Generate CSV content
      const csvContent = `Weekly Learning Report
Generated: ${format(new Date(), 'PPP')}
Week: ${format(weekStart, 'MMM d')} - ${format(weekEnd, 'MMM d, yyyy')}

STUDENT PROFILE
Name: ${profile.display_name || 'Student'}
Current Level: ${profile.level}
Total XP: ${profile.xp_points}
Current Streak: ${profile.streak_days} days
Coins Earned: ${profile.coins}

WEEKLY SUMMARY
Lessons Completed: ${lessonsCompleted}
Quiz Attempts: ${quizAttempts}
Correct Answers: ${correctAnswers}
Accuracy: ${quizAttempts > 0 ? Math.round((correctAnswers / quizAttempts) * 100) : 0}%
XP Earned This Week: ${xpEarned}
Days Active: ${daysWithProgress}/7

DAILY BREAKDOWN
Date,XP Earned,Questions Completed,Streak Maintained
${goals.map(g => 
  `${g.goal_date},${g.earned_xp},${g.completed_questions},${g.streak_maintained ? 'Yes' : 'No'}`
).join('\n')}

---
Report generated by LevelHubAI Learning Platform
`;

      // Create and download the file
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `weekly-report-${format(new Date(), 'yyyy-MM-dd')}.csv`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast.success('Weekly report exported successfully!');
    } catch (error) {
      console.error('Export error:', error);
      toast.error('Failed to export report');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={generateReport}
      disabled={isExporting}
      className="gap-2"
    >
      {isExporting ? (
        <Loader2 className="h-4 w-4 animate-spin" />
      ) : (
        <FileDown className="h-4 w-4" />
      )}
      Export Report
    </Button>
  );
};
